### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by eyedol** [netlify/victor-hugo#24]
Spinning this off a docker image will ease a lot of setup and deployment efforts. I don't have to install node and npm stuff on my host machine. Would help hugely with teams when it comes to development collaboration. Alas, but it's working on my machine!

**Comment by calavera** [comment]
We've decided to not do this. Adding a Docker setup would actually complicate things further, rather than easy them, as people would need to know how to use Docker. We rather ask people to learn how to use the tools required to run this project, than to ask them to learn how to use an indirect dependency.

**Comment by jhabdas** [comment]
Here's a sample Dockerfile I used for the last time I was working with Webpack. I found it important to _simplify_ cross-environment compatibility as Webpack is extremely complex.

https://github.com/jhabdas/react-native-webpack-starter-kit/blob/master/Dockerfile

This Dockerfile could further be improved using the microcontaininer approach used in #25 to help individuals achieve a repeatable build process and a 1 click environment setups for Victor Hugo if ported thoughtfully.
